# Generated by Django 5.0.1 on 2024-05-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
