# Generated by Django 5.0.1 on 2024-05-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0004_status_requesttraining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('User', 'User'), ('Maker', 'Maker'), ('Checker', 'Checker'), ('HOD', 'HOD')], max_length=20),
        ),
    ]
