# Generated by Django 5.0.1 on 2024-05-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0005_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
