# Generated by Django 5.0.1 on 2024-05-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0006_customuser_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttraining',
            name='comment',
        ),
        migrations.AddField(
            model_name='requesttraining',
            name='checker_approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requesttraining',
            name='checker_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requesttraining',
            name='hod_approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requesttraining',
            name='hod_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requesttraining',
            name='user_comment',
            field=models.TextField(blank=True),
        ),
    ]
