# Generated by Django 5.0.1 on 2024-05-22 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0007_remove_requesttraining_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HODTrainingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_training', models.CharField(blank=True, max_length=255)),
                ('hod_comment', models.TextField(blank=True)),
                ('checker_comment', models.TextField(blank=True)),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('checker_approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trainings', to='useri.customuser')),
                ('hod_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_assignments', to='useri.customuser')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='useri.status')),
                ('training_programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='useri.trainingprogramme')),
            ],
        ),
    ]
