# Generated by Django 5.0.1 on 2024-05-27 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0009_remove_hodtrainingassignment_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttraining',
            name='hod_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_requests', to='useri.customuser'),
        ),
    ]
