# Generated by Django 5.0.1 on 2024-05-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0011_hodtrainingassignment_hod_approval_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
