# Generated by Django 5.0.1 on 2024-05-29 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0012_venuemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_type', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('custom_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings_conducted', to='useri.customuser')),
                ('training_programmes', models.ManyToManyField(related_name='trainers', to='useri.trainingprogramme')),
            ],
        ),
    ]
