# Generated by Django 5.0.1 on 2024-05-29 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0016_trainingsession_custom_training_programme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='from_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='to_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
    ]
