# Generated by Django 5.0.1 on 2024-05-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0017_trainingsession_date_trainingsession_from_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='to_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
