# Generated by Django 5.0.1 on 2024-05-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0018_alter_trainingsession_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemaster',
            name='venue_type',
            field=models.CharField(choices=[('Classroom', 'Classroom'), ('On Job', 'On Job'), ('External', 'External'), ('Online', 'Online')], default='Classroom', max_length=20),
        ),
    ]
