# Generated by Django 5.0.1 on 2024-05-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0019_venuemaster_venue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='online_training_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
