# Generated by Django 5.0.1 on 2024-05-30 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0021_trainingsession_online_training_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='online_training_file',
            field=models.FileField(blank=True, null=True, upload_to='online_training_files/'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='online_training_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useri.trainermaster'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useri.venuemaster'),
        ),
    ]
