# Generated by Django 5.0.1 on 2024-05-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0022_alter_trainingsession_online_training_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='deadline_to_complete',
            field=models.DateField(blank=True, null=True),
        ),
    ]
