# Generated by Django 5.0.1 on 2024-06-01 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0023_trainingsession_deadline_to_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useri.customuser')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useri.trainingsession')),
            ],
        ),
    ]
