# Generated by Django 5.0.1 on 2024-06-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0024_attendancemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogramme',
            name='validity',
            field=models.IntegerField(default=2),
        ),
    ]
