# Generated by Django 5.0.1 on 2024-06-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0025_trainingprogramme_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='selected_participants',
            field=models.ManyToManyField(blank=True, related_name='selected_trainings', to='useri.customuser'),
        ),
    ]
