# Generated by Django 5.0.1 on 2024-06-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0028_remove_customuser_passport_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='card_active_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='card_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='card_validity',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_leaving',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='emergency_contact_no',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='emergency_contact_person',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='identification_mark_1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='identification_mark_2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='section',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='shift_group',
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='user_departments', to='useri.customuser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='department_members', to='useri.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
