# Generated by Django 5.0.1 on 2024-06-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0030_remove_superiorassignedtraining_can_assign_trainings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttraining',
            name='is_final_approver',
        ),
    ]
