# Generated by Django 5.0.1 on 2024-06-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0031_remove_requesttraining_is_final_approver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttraining',
            name='hod_user',
        ),
        migrations.AddField(
            model_name='requesttraining',
            name='final_approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
