# Generated by Django 5.0.1 on 2024-06-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0032_remove_requesttraining_hod_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superiorassignedtraining',
            name='hod_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='superiorassignedtraining',
            name='other_training',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
