# Generated by Django 5.0.1 on 2024-06-08 04:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0033_superiorassignedtraining_hod_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superiorassignedtraining',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
