# Generated by Django 5.0.1 on 2024-06-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0034_superiorassignedtraining_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='superiorassignedtraining',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_superior_trainings', to='useri.customuser'),
        ),
    ]
