# Generated by Django 5.0.1 on 2024-06-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0035_superiorassignedtraining_assigned_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'get_latest_by': 'approval_timestamp'},
        ),
        migrations.AlterModelOptions(
            name='superiorassignedtraining',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AlterField(
            model_name='superiorassignedtraining',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_trainings', to='useri.customuser'),
        ),
    ]
