# Generated by Django 5.0.1 on 2024-06-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0037_approval_superior_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='action',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], default='approve', max_length=10),
        ),
    ]
