# Generated by Django 5.0.1 on 2024-06-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0039_requesttraining_is_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttraining',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='superiorassignedtraining',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
