# Generated by Django 5.0.1 on 2024-06-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0040_requesttraining_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='action',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
