# Generated by Django 5.0.1 on 2024-06-08 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0041_alter_approval_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttraining',
            name='current_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_requests', to='useri.customuser'),
        ),
    ]
