# Generated by Django 5.0.1 on 2024-06-08 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0042_requesttraining_current_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='superiorassignedtraining',
            name='current_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_superior_assignments', to='useri.customuser'),
        ),
    ]
