# Generated by Django 5.0.1 on 2024-06-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0043_superiorassignedtraining_current_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='superiorassignedtraining',
            name='final_approval_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
