# Generated by Django 5.0.1 on 2024-06-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0044_superiorassignedtraining_final_approval_timestamp'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
