# Generated by Django 5.0.1 on 2024-06-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0045_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='associates',
            field=models.ManyToManyField(blank=True, related_name='associated_departments', to='useri.customuser'),
        ),
    ]
