# Generated by Django 5.0.1 on 2024-06-13 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0046_department_associates'),
    ]

    operations = [
        migrations.AddField(
            model_name='superiorassignedtraining',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='useri.status'),
        ),
    ]
