# Generated by Django 5.0.1 on 2024-06-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0047_superiorassignedtraining_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='card_validity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
