# Generated by Django 5.0.1 on 2024-06-15 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0049_trainingsession_finalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removal_reasons', models.JSONField(blank=True, default=dict)),
                ('approved', models.BooleanField(default=False)),
                ('approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useri.department')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useri.customuser')),
                ('removed_participants', models.ManyToManyField(blank=True, related_name='removed_trainings', to='useri.customuser')),
                ('selected_participants', models.ManyToManyField(blank=True, related_name='approved_trainings', to='useri.customuser')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useri.trainingsession')),
            ],
        ),
    ]
