# Generated by Django 5.0.1 on 2024-06-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0052_trainingapproval_pending_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingapproval',
            name='comment',
        ),
        migrations.AlterField(
            model_name='trainingapproval',
            name='removal_reasons',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='trainingapproval',
            name='removed_participants',
            field=models.ManyToManyField(related_name='removed_participants', to='useri.customuser'),
        ),
        migrations.AlterField(
            model_name='trainingapproval',
            name='selected_participants',
            field=models.ManyToManyField(related_name='selected_participants', to='useri.customuser'),
        ),
    ]
