# Generated by Django 5.0.1 on 2024-06-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0053_remove_trainingapproval_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingapproval',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
