# Generated by Django 5.0.1 on 2024-06-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0055_trainingsession_checker_finalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='needs_hod_nomination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='nomination_counts',
            field=models.JSONField(default=dict),
        ),
    ]
