# Generated by Django 5.0.1 on 2024-06-27 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0056_trainingsession_needs_hod_nomination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_employees', models.IntegerField(default=0)),
                ('required_associates', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useri.department')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useri.customuser')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_counts', to='useri.trainingsession')),
            ],
        ),
    ]
