# Generated by Django 5.0.1 on 2024-07-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0059_remove_trainingapproval_attendance_frozen'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='attendance_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
