# Generated by Django 5.0.1 on 2024-07-03 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0060_trainingsession_attendance_frozen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_number', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('duration', models.FloatField()),
                ('question_1', models.TextField()),
                ('question_2', models.TextField()),
                ('question_3', models.TextField()),
                ('question_4', models.TextField()),
                ('question_5', models.TextField()),
                ('question_6', models.TextField()),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useri.attendancemaster')),
            ],
        ),
    ]
