# Generated by Django 5.0.1 on 2024-07-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0061_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='designation',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='programme_title',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question_4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question_5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='question_6',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
