# Generated by Django 5.0.1 on 2024-07-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0062_feedback_designation_feedback_programme_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='programme_title',
            field=models.CharField(max_length=255),
        ),
    ]
