# Generated by Django 5.0.1 on 2024-07-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0063_alter_feedback_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='question_6',
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_6a',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_6b',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_6c',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_6d',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_6e',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_7',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_8',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_8_quality_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='question_9',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
