# Generated by Django 5.0.1 on 2024-07-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0064_remove_feedback_question_6_feedback_question_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_top_authority',
            field=models.BooleanField(default=False),
        ),
    ]
