# Generated by Django 5.0.1 on 2024-08-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useri', '0065_customuser_is_top_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogramme',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
